# Generated by Django 4.2.7 on 2025-07-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("COMPUTER", "Computer"),
                            ("SERVER", "Server"),
                            ("ROUTER", "Router"),
                            ("SWITCH", "Switch"),
                            ("PRINTER", "Printer"),
                            ("MOBILE", "Mobile Device"),
                            ("IOT", "IoT Device"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="device_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_online", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("LAN", "LAN"),
                            ("WIFI", "WiFi"),
                            ("BLUETOOTH", "Bluetooth"),
                            ("USB", "USB"),
                            ("SERIAL", "Serial"),
                            ("OTHER", "Other"),
                        ],
                        default="LAN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="network_api.device",
                    ),
                ),
                (
                    "target_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="network_api.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="config_files/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_files",
                        to="network_api.device",
                    ),
                ),
            ],
        ),
    ]
